# Generated by Django 3.2.20 on 2023-07-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PontoTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('aprovado', models.BooleanField()),
                ('atracoes', models.ManyToManyField(to='atracoes.Atracao')),
            ],
            options={
                'verbose_name': 'Potos Turístico',
                'verbose_name_plural': 'Pontos Turísticos',
            },
        ),
    ]
