# Generated by Django 3.2.20 on 2023-07-07 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enderece',
            new_name='Endereco',
        ),
    ]
